kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customer_addresses.create
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customer_addresses.delete
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customer_addresses.findAll
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customers.authenticate
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customers.create
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customers.findAll
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customers.findOne
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.customers.update
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.dishes.create
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.dishes.findAll
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.dishes.findById
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.dishes.update
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.favourites.create
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.favourites.delete
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.favourites.findAll
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.orders.fetchOrdersForCustomer
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.orders.fetchOrdersForRestaurant
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.orders.fetchpageNumbersForCustomerOrders
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.orders.fetchpageNumbersForRestaurantOrders
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.orders.placeOrder
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.orders.updateStatus
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.response_topic
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurant_addresses.create
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurant_addresses.findOne
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurants.authenticate
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurants.create
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurants.findAll
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurants.findOne
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurants.findSearchedItems
kafka-topics --create --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092 --topic lab3.restaurants.update
