kafka-topics --delete  --bootstrap-server localhost:9092 --topic customer_addresses.create
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customer_addresses.delete
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customer_addresses.findAll
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customers.authenticate
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customers.create
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customers.findAll
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customers.findOne
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customers.update
kafka-topics --delete  --bootstrap-server localhost:9092 --topic customers_addresses.findAll
kafka-topics --delete  --bootstrap-server localhost:9092 --topic dishes.create
kafka-topics --delete  --bootstrap-server localhost:9092 --topic dishes.findAll
kafka-topics --delete  --bootstrap-server localhost:9092 --topic dishes.findById
kafka-topics --delete  --bootstrap-server localhost:9092 --topic dishes.findOne
kafka-topics --delete  --bootstrap-server localhost:9092 --topic dishes.update
kafka-topics --delete  --bootstrap-server localhost:9092 --topic favourites.create
kafka-topics --delete  --bootstrap-server localhost:9092 --topic favourites.delete
kafka-topics --delete  --bootstrap-server localhost:9092 --topic favourites.findAll
kafka-topics --delete  --bootstrap-server localhost:9092 --topic order.placeOrder
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.fetchOrdersForCustomer
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.fetchOrdersForRestaurant
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.fetchPageNumbersForRestaurantOrders
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.fetchpageNumbersForCustomerOrders
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.fetchpageNumbersForRestaurantOrders
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.placeOrder
kafka-topics --delete  --bootstrap-server localhost:9092 --topic orders.updateStatus
kafka-topics --delete  --bootstrap-server localhost:9092 --topic response_topic
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurant_addresses.create
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurant_addresses.findOne
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurants.authenticate
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurants.create
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurants.findAll
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurants.findOne
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurants.findSearchedItems
kafka-topics --delete  --bootstrap-server localhost:9092 --topic restaurants.update
